import type { Metadata } from 'next';
import {
    Geist,
    Kalam,
    Cedarville_Cursive,
    Comic_Relief,
    New_Rocker,
    Jersey_10,
} from 'next/font/google';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const kalam = Kalam({
    variable: '--font-kalam',
    subsets: ['latin'],
    weight: '400',
});

const cedarvilleCursive = Cedarville_Cursive({
    variable: '--font-cedarville-cursive',
    subsets: ['latin'],
    weight: '400',
});

const comicRelief = Comic_Relief({
    variable: '--font-comic-relief',
    subsets: ['latin'],
    weight: '400',
});

const newRocker = New_Rocker({
    variable: '--font-new-rocker',
    subsets: ['latin'],
    weight: '400',
});

const jersey10 = Jersey_10({
    variable: '--font-jersey-10',
    subsets: ['latin'],
    weight: '400',
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`
                ${geistSans.variable} 
                ${kalam.variable}
                ${cedarvilleCursive.variable}
                ${comicRelief.variable}
                ${newRocker.variable}
                ${jersey10.variable}
            `}
            >
                {children}
            </body>
        </html>
    );
}

/*
regular sans-serif (geist)
handwriting (kalam)
cursive (cerdarville cursive)
comic sans (comic releif)
goth (new rocker)
pixel (jersey 10)
*/
